<template>
  <el-dialog
    v-model="dialogVisible"
    :title="$t('rfq.pr.generatePrExcel')"
    width="700px"
    :close-on-click-modal="false"
    @close="handleClose"
  >
    <div class="pr-excel-generator">
      <!-- Selected Line Items Summary -->
      <el-alert
        :title="$t('rfq.pr.selectItemsToExport')"
        type="info"
        :closable="false"
        show-icon
        class="selected-items-alert"
      >
        <div class="items-selection">
          <el-alert
            v-if="hasMultipleCurrencies"
            type="warning"
            :closable="false"
            show-icon
            class="currency-warning"
          >
            <template #title>
              {{ $t('rfq.pr.multipleCurrencyWarning') }}
            </template>
            <div>
              {{ $t('rfq.pr.multipleCurrencyHint') }}
              <ul class="currency-list">
                <li v-for="(items, currency) in itemsByCurrency" :key="currency">
                  {{ currency }}: {{ items.length }} {{ $t('rfq.pr.items') }}
                </li>
              </ul>
            </div>
          </el-alert>
          <div class="selection-header">
            <el-checkbox
              :model-value="isAllSelected"
              :indeterminate="isIndeterminate"
              @change="handleSelectAllChange"
            >
              {{ $t('rfq.pr.selectAll') }} ({{ selectedIds.length }}/{{ lineItems.length }})
            </el-checkbox>
          </div>
          <el-scrollbar max-height="280px">
            <el-checkbox-group v-model="selectedIds" class="item-checkbox-group">
              <div
                v-for="item in lineItems"
                :key="item.id"
                class="item-row"
                :class="{ 'is-selected': selectedIds.includes(item.id) }"
              >
                <el-checkbox :label="item.id" class="item-checkbox">
                  <div class="item-info">
                    <el-tag size="small" type="primary">#{{ item.lineNumber }}</el-tag>
                    <span class="item-name">{{ item.itemName || item.description }}</span>
                    <span class="item-qty">{{ item.quantity }} {{ item.unit }}</span>
                  </div>
                </el-checkbox>

                <div v-if="item.selectedQuote" class="quote-info">
                  <span class="supplier">{{ item.selectedQuote.supplierName }}</span>
                  <span class="price">
                    {{ item.selectedQuote.currency }} {{ formatPrice(item.selectedQuote.unitPrice) }}
                  </span>
                  <span class="total">
                    {{ $t('rfq.pr.total') }}:
                    {{ item.selectedQuote.currency }} {{ formatPrice(item.selectedQuote.totalPrice) }}
                  </span>
                </div>
                <div v-else class="quote-warning">
                  <el-tag type="warning" size="small">{{ $t('rfq.pr.noQuoteSelected') }}</el-tag>
                </div>
              </div>
            </el-checkbox-group>
          </el-scrollbar>
        </div>
      </el-alert>

      <!-- PR Configuration Form -->
      <el-form
        ref="formRef"
        :model="form"
        label-position="top"
        class="pr-form"
      >
        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item :label="$t('rfq.pr.prNumber')">
              <el-input
                v-model="form.prNumber"
                :placeholder="$t('rfq.pr.autoGenerated')"
                clearable
              >
                <template #append>
                  <el-button @click="handleAutoGeneratePrNumber">
                    {{ $t('rfq.pr.autoGenerate') }}
                  </el-button>
                </template>
              </el-input>
            </el-form-item>
          </el-col>

          <el-col :span="12">
            <el-form-item :label="$t('rfq.pr.department')">
              <el-input
                v-model="form.department"
                :placeholder="rfq?.requestingDepartment || $t('rfq.pr.departmentPlaceholder')"
                clearable
              />
            </el-form-item>
          </el-col>
        </el-row>

        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item :label="$t('rfq.pr.accountNo')">
              <el-input
                v-model="form.accountNo"
                :placeholder="$t('rfq.pr.accountNoPlaceholder')"
                clearable
              />
            </el-form-item>
          </el-col>
        </el-row>

        <!-- Instructions -->
        <el-alert
          :title="$t('rfq.pr.instructions')"
          type="success"
          :closable="false"
          show-icon
        >
          <ul class="instruction-list">
            <li>{{ $t('rfq.pr.instruction1') }}</li>
            <li>{{ $t('rfq.pr.instruction2') }}</li>
            <li>{{ $t('rfq.pr.instruction3') }}</li>
            <li>{{ $t('rfq.pr.instruction4') }}</li>
          </ul>
        </el-alert>
      </el-form>
    </div>

    <template #footer>
      <div class="dialog-footer">
        <el-button @click="handleClose">{{ $t('common.cancel') }}</el-button>
        <el-button
          type="primary"
          :loading="generating"
          :disabled="selectedIds.length === 0"
          :icon="Download"
          @click="handleGenerateAndDownload"
        >
          {{ $t('rfq.pr.generateAndDownload') }}
          <template v-if="selectedIds.length">
            ({{ selectedIds.length }})
          </template>
        </el-button>
      </div>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref, reactive, computed, watch, onMounted, onUnmounted, nextTick } from 'vue'
import { Download } from '@element-plus/icons-vue'
import { ElMessageBox } from 'element-plus'
import { useI18n } from 'vue-i18n'
import { generatePrExcel } from '@/api/rfq'
import { useNotification } from "@/composables";

const notification = useNotification();

interface QuoteSummary {
  id: number
  supplierId: number
  supplierName: string
  supplierCode?: string
  currency: string
  unitPrice: number
  totalPrice: number
  deliveryPeriod?: number | string | null
}

interface LineItemQuoteSummary {
  id: number
  lineNumber: number
  itemName?: string
  description?: string
  quantity: number
  unit: string
  currency?: string
  status?: string
  selectedQuoteId?: number | null
  selectedQuote?: QuoteSummary | null
}

const props = defineProps<{
  modelValue: boolean
  rfqId: number
  rfq: any
  lineItems: LineItemQuoteSummary[]
  preselectedItemId?: number | null
}>()

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
  'success': []
}>()

const { t } = useI18n()

const dialogVisible = computed({
  get: () => props.modelValue,
  set: (value) => emit('update:modelValue', value)
})

const formRef = ref()
const generating = ref(false)
const selectedIds = ref<number[]>([])
const isMounted = ref(false)

const ensureDomReady = async () => {
  if (!isMounted.value || typeof document === "undefined" || typeof window === "undefined") {
    return false
  }
  await nextTick()
  return true
}

const form = reactive({
  prNumber: '',
  department: '',
  accountNo: ''
})

const normalizedLineItems = computed<LineItemQuoteSummary[]>(() =>
  Array.isArray(props.lineItems) ? props.lineItems : []
)

const isAllSelected = computed(() => {
  return normalizedLineItems.value.length > 0 && selectedIds.value.length === normalizedLineItems.value.length
})

const isIndeterminate = computed(() => {
  return selectedIds.value.length > 0 && !isAllSelected.value
})

const itemsByCurrency = computed<Record<string, LineItemQuoteSummary[]>>(() => {
  const groups: Record<string, LineItemQuoteSummary[]> = {}
  normalizedLineItems.value.forEach((item) => {
    const currency = item.selectedQuote?.currency || item.currency || 'CNY'
    if (!groups[currency]) {
      groups[currency] = []
    }
    groups[currency].push(item)
  })
  return groups
})

const hasMultipleCurrencies = computed(() => Object.keys(itemsByCurrency.value).length > 1)

onMounted(() => {
  isMounted.value = true
})

onUnmounted(() => {
  isMounted.value = false
})

// Initialize department and selection when dialog opens
watch(
  () => props.modelValue,
  (visible) => {
    if (visible) {
      if (props.rfq) {
        form.department = props.rfq.requestingDepartment || ''
      }
      selectedIds.value = computeInitialSelection()
    } else {
      selectedIds.value = []
    }
  }
)

// Keep selections in sync with available line items
watch(
  () => props.lineItems,
  (newItems) => {
    const safeItems = Array.isArray(newItems) ? newItems : []
    const availableIds = new Set(safeItems.map((item) => item.id))
    selectedIds.value = selectedIds.value.filter((id) => availableIds.has(id))

    if (props.modelValue && selectedIds.value.length === 0 && safeItems.length > 0) {
      selectedIds.value = computeInitialSelection()
    }
  },
  { deep: true }
)

/**
 * Auto-generate PR number
 * Format: HZ_{DEPT}_{YYYYMMDD}{SEQ}
 */
function handleAutoGeneratePrNumber() {
  const today = new Date()
  const year = today.getFullYear()
  const month = String(today.getMonth() + 1).padStart(2, '0')
  const day = String(today.getDate()).padStart(2, '0')
  const dateStr = `${year}${month}${day}`

  const dept = (form.department || props.rfq?.requestingDepartment || 'IT').toUpperCase()
  const seq = '001'  // Simplified, backend will handle actual sequence

  form.prNumber = `HZ_${dept}_${dateStr}${seq}`
}

function computeInitialSelection() {
  const safeItems = normalizedLineItems.value
  if (safeItems.length === 0) {
    return []
  }

  if (props.preselectedItemId && safeItems.some((item) => item.id === props.preselectedItemId)) {
    return [props.preselectedItemId]
  }

  return safeItems.map((item) => item.id)
}

function handleSelectAllChange(val: boolean) {
  selectedIds.value = val ? normalizedLineItems.value.map((item) => item.id) : []
}

function formatPrice(value?: number | string | null) {
  if (value === null || value === undefined || value === '') {
    return '0.00'
  }

  const numeric = Number(value)
  if (Number.isNaN(numeric)) {
    return String(value)
  }

  return new Intl.NumberFormat('zh-CN', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 4
  }).format(numeric)
}

function handleInvalidStatusError(error: any) {
  const invalidItems = error?.details?.invalidItems ?? []

  if (!invalidItems.length) {
    notification.warning(error?.message || t('rfq.pr.invalidStatusMessage'))
    return
  }

  const itemDetails = invalidItems
    .map((item: any) => {
      const lineLabel = item.lineNumber ? `#${item.lineNumber}` : `ID:${item.id}`
      const reason = item.reason || item.status || 'invalid'
      return `${lineLabel} - ${reason}`
    })
    .join('\n')

  ElMessageBox.alert(
    `<div>${t('rfq.pr.invalidStatusMessage')}<pre style="background:#f5f5f5;padding:10px;margin-top:10px;max-height:200px;overflow:auto;">${itemDetails}</pre></div>`,
    t('rfq.pr.invalidStatusTitle'),
    {
      dangerouslyUseHTMLString: true,
      type: 'warning',
      confirmButtonText: t('common.ok')
    }
  )

  const invalidIds = new Set(invalidItems.map((item: any) => item.id))
  selectedIds.value = selectedIds.value.filter((id) => !invalidIds.has(id))
}

function handleMissingQuoteError(error: any) {
  const missingItems = error?.details?.missingQuoteItems ?? []

  if (!missingItems.length) {
    notification.error(error?.message || t('rfq.pr.generateFailed'))
    return
  }

  const itemList = missingItems
    .map((item: any) => (item.lineNumber ? `#${item.lineNumber}` : `ID:${item.id}`))
    .join(', ')

  notification.error(
    `${t('rfq.pr.missingQuoteMessage')}: ${itemList}`,
    undefined,
    { duration: 10000, showClose: true }
  )

  const missingIds = new Set(missingItems.map((item: any) => item.id))
  selectedIds.value = selectedIds.value.filter((id) => !missingIds.has(id))
}

/**
 * Generate and download PR Excel
 */
async function handleGenerateAndDownload() {
  try {
    // Prevent double submission
    if (generating.value) {
      console.warn('[PR Excel] Generation already in progress, ignoring duplicate request')
      return
    }

    generating.value = true

    if (normalizedLineItems.value.length === 0) {
      notification.warning(t('rfq.pr.noLineItemsSelected'))
      return
    }

    if (selectedIds.value.length === 0) {
      notification.warning(t('rfq.pr.pleaseSelectItems'))
      return
    }

    const availableIds = new Set(normalizedLineItems.value.map((item) => item.id))
    const lineItemIds = selectedIds.value.filter((id) => availableIds.has(id))

    if (lineItemIds.length === 0) {
      notification.error(t('rfq.pr.noLineItemsSelected'))
      return
    }

    if (lineItemIds.length > 500) {
      notification.warning({
        message: t('rfq.pr.exportCount', { count: lineItemIds.length }),
        duration: 5000
      })
    }

    // Show progress message for large generations
    let progressMessage: any
    if (lineItemIds.length > 100) {
      progressMessage = notification.info({
        message: t('rfq.pr.generatingProgress', { count: lineItemIds.length }),
        duration: 0, // Don't auto-close
        showClose: false
      })
    }

    try {
      // Call API to generate Excel
      const blob = await generatePrExcel(
        props.rfqId,
        lineItemIds,
        {
          prNumber: form.prNumber || undefined,
          department: form.department || undefined,
          accountNo: form.accountNo || undefined
        }
      )

      // Close progress message
      if (progressMessage) {
        progressMessage.close()
      }

      // Validate blob size
      if (blob.size < 100 * 1024) {
        console.warn(`[PR Excel] Generated file is small: ${(blob.size / 1024).toFixed(2)} KB`)
        notification.warning({
          message: t('rfq.pr.fileSmallWarning', { size: (blob.size / 1024).toFixed(2) }),
          duration: 8000
        })
      } else if (blob.size > 50 * 1024 * 1024) {
        notification.error({
          message: t('rfq.pr.fileLargeError', { size: (blob.size / 1024 / 1024).toFixed(2) }),
          duration: 8000
        })
        return
      }

      if (!(await ensureDomReady())) {
        return
      }

      // Create download link and trigger download
      const url = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url

      // Generate filename with .xlsm extension (with VBA macros)
      const timestamp = new Date().getTime()
      const prNum = form.prNumber || `HZ_PR_${timestamp}`
      link.download = `PR_(${prNum})_${timestamp}.xlsm`

      // Trigger download
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)

      // Clean up
      window.URL.revokeObjectURL(url)

      notification.success({
        message: t('rfq.pr.generateSuccessWithSize', { size: (blob.size / 1024).toFixed(2) }),
        duration: 5000
      })

      // Emit success and close dialog
      emit('success')
      handleClose()
    } catch (apiError: any) {
      // Close progress message on error
      if (progressMessage) {
        progressMessage.close()
      }

      throw apiError // Re-throw to outer catch for error handling
    }
  } catch (error: any) {
    console.error('[PR Excel] Generation error:', error)

    if (error?.code === 'INVALID_LINE_ITEM_STATUS') {
      handleInvalidStatusError(error)
    } else if (error?.code === 'MISSING_SELECTED_QUOTE') {
      handleMissingQuoteError(error)
    } else {
      const errorCode = error?.code || 'UNKNOWN'
      const errorMessage = error?.message || t('rfq.pr.generateFailed')

      if (errorCode === 'NO_VALID_LINE_ITEMS' || errorCode === 'INVALID_LINE_ITEMS') {
        notification.warning({
          message: errorMessage,
          duration: 8000,
          showClose: true
        })
      } else if (errorCode === 'TEMPLATE_ERROR' || errorCode === 'FILE_TOO_SMALL') {
        notification.error({
          message: errorMessage,
          duration: 10000,
          showClose: true
        })
      } else {
        notification.error({
          message: errorMessage,
          duration: 8000,
          showClose: true
        })
      }
    }

    if (error?.details) {
      console.error('[PR Excel] Error details:', error.details)
    }
  } finally {
    generating.value = false
  }
}

function handleClose() {
  // Reset form
  form.prNumber = ''
  form.department = ''
  form.accountNo = ''
  selectedIds.value = []
  emit('update:modelValue', false)
}
</script>

<style scoped lang="scss">
.pr-excel-generator {
  .selected-items-alert {
    margin-bottom: 24px;

    .items-selection {
      margin-top: 12px;

      .selection-header {
        margin-bottom: 12px;
        padding-bottom: 8px;
        border-bottom: 1px solid #ebeef5;
      }

      .currency-warning {
        margin-bottom: 12px;

        .currency-list {
          margin: 8px 0 0;
          padding-left: 20px;
          font-size: 13px;
          color: #606266;

          li {
            margin-bottom: 4px;
          }
        }
      }

      .item-checkbox-group {
        display: flex;
        flex-direction: column;
        gap: 8px;
      }

      .item-row {
        border: 1px solid #ebeef5;
        border-radius: 4px;
        padding: 12px;
        transition: border-color 0.2s ease, background-color 0.2s ease;

        &.is-selected {
          border-color: #409eff;
          background-color: #f0f9ff;
        }

        .item-checkbox {
          width: 100%;
        }

        .item-info {
          display: flex;
          align-items: center;
          gap: 12px;
          font-size: 13px;

          .item-name {
            flex: 1;
            color: #606266;
          }

          .item-qty {
            color: #909399;
            white-space: nowrap;
          }
        }

        .quote-info {
          margin-top: 10px;
          padding-left: 28px;
          display: flex;
          gap: 16px;
          font-size: 12px;
          color: #606266;

          .supplier {
            color: #67c23a;
            font-weight: 600;
          }

          .price,
          .total {
            color: #e6a23c;
            white-space: nowrap;
          }
        }

        .quote-warning {
          margin-top: 10px;
          padding-left: 28px;
        }
      }
    }
  }

  .pr-form {
    margin-top: 20px;

    :deep(.el-form-item__label) {
      font-weight: 600;
      color: #303133;
    }

    .instruction-list {
      margin: 8px 0 0;
      padding-left: 20px;
      font-size: 13px;
      line-height: 1.8;
      color: #606266;

      li {
        margin-bottom: 4px;
      }
    }
  }
}

.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
}
</style>
