import { Supplier, SupplierStage, SupplierStatus, User, UserRole } from "@/types";

const createRatingsSummary = (): Supplier["ratingsSummary"] => ({
  totalEvaluations: 0,
  overallAverage: null,
  avgOnTimeDelivery: null,
  avgQualityScore: null,
  avgServiceScore: null,
  avgCostScore: null,
});

export const mockUsers: User[] = [
  {
    id: "admin001",
    name: "Alex Administrator",
    role: UserRole.ADMIN,
    email: "admin@example.com",
    permissions: [
      "view_all",
      "create_supplier",
      "edit_supplier",
      "delete_supplier",
      "approve_supplier",
    ],
  },
  {
    id: "pur001",
    name: "Piper Purchaser",
    role: UserRole.PURCHASER,
    email: "purchaser@example.com",
    permissions: ["view_own", "create_supplier", "approve_supplier"],
  },
  {
    id: "pm001",
    name: "Morgan Director",
    role: UserRole.PURCHASE_MANAGER,
    email: "director@example.com",
    permissions: ["view_all", "approve_supplier"],
  },
  {
    id: "fm001",
    name: "Finley Finance",
    role: UserRole.FINANCE_MANAGER,
    email: "finance@example.com",
    permissions: ["view_all", "approve_supplier"],
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: 1,
    companyName: "Prime Materials Ltd.",
    companyId: "MAT001",
    contactPerson: "Jordan Smith",
    contactPhone: "+1-555-1000",
    contactEmail: "jordan@primematerials.com",
    category: "Raw material",
    address: "100 Industrial Way, Austin, TX",
    status: SupplierStatus.APPROVED,
    stage: SupplierStage.OFFICIAL,
    currentApprover: null,
    createdBy: "pur001",
    createdAt: "2024-01-15T10:30:00",
    approvalHistory: [
      {
        step: "pending_purchaser",
        approver: "pur001",
        result: "approved",
        date: "2024-01-16T09:00:00",
        comments: "Documentation verified. Recommended for approval.",
      },
    ],
    notes: "Strategic supplier for core materials",
    tags: [],
    documents: [],
    ratingsSummary: createRatingsSummary(),
    latestRating: null,
    contracts: [],
    files: [],
    fileApprovals: [],
    pendingChangeRequest: null,
    profileCompletion: 100,
    documentCompletion: 100,
    completionScore: 100,
    completionStatus: "complete",
    missingRequirements: [],
    complianceSummary: {
      requiredProfileFields: [],
      missingProfileFields: [],
      requiredDocumentTypes: [],
      missingDocumentTypes: [],
      isProfileComplete: true,
      isDocumentComplete: true,
      isComplete: true,
      profileScore: 100,
      documentScore: 100,
      overallScore: 100,
      completionCategory: "complete",
      missingItems: [],
    },
  },
  {
    id: 2,
    companyName: "Innova Tech Corp.",
    companyId: "TECH002",
    contactPerson: "Taylor Lee",
    contactPhone: "+1-555-2200",
    contactEmail: "taylor@innovatech.com",
    category: "IT",
    address: "22 Innovation Drive, Seattle, WA",
    status: SupplierStatus.PENDING_PURCHASE_MANAGER,
    stage: SupplierStage.TEMPORARY,
    currentApprover: "pm001",
    createdBy: "pur001",
    createdAt: "2024-01-20T08:45:00",
    approvalHistory: [],
    notes: "Provides device lifecycle services",
    tags: [],
    documents: [],
    ratingsSummary: createRatingsSummary(),
    latestRating: null,
    contracts: [],
    files: [],
    fileApprovals: [],
    pendingChangeRequest: null,
    profileCompletion: 100,
    documentCompletion: 100,
    completionScore: 100,
    completionStatus: "complete",
    missingRequirements: [],
    complianceSummary: {
      requiredProfileFields: [],
      missingProfileFields: [],
      requiredDocumentTypes: [],
      missingDocumentTypes: [],
      isProfileComplete: true,
      isDocumentComplete: true,
      isComplete: true,
      profileScore: 100,
      documentScore: 100,
      overallScore: 100,
      completionCategory: "complete",
      missingItems: [],
    },
  },
];
